{"uid":"8af5bbab842588dc","name":"WS-TC8 - Subscribe with invalid depth value","fullName":"WebSocket API: book.{instrument_name}.{depth}: WS-TC8 - Subscribe with invalid depth value","historyId":"2d217964bf4e3b9356ccb17d0f9bdc7e","time":{"start":1751007248960,"stop":1751007263980,"duration":15020},"status":"failed","statusMessage":"AssertionError: Expected error response but none found\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/ws_steps.py\", line 125, in step_then_ws_expected\n    assert has_error, \"Expected error response but none found\"\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected error response but none found\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/ws_steps.py\", line 125, in step_then_ws_expected\n    assert has_error, \"Expected error response but none found\"\n","steps":[{"name":"Given WS test input \"depth='abc' or -10\"","time":{"start":1751007248960,"stop":1751007263979,"duration":15019},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then WS expected result should be \"error message returned\"","time":{"start":1751007263979,"stop":1751007263980,"duration":1},"status":"failed","statusMessage":"AssertionError: Expected error response but none found\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/ws_steps.py\", line 125, in step_then_ws_expected\n    assert has_error, \"Expected error response but none found\"\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"WebSocket API: book.{instrument_name}.{depth}"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8af5bbab842588dc.json","parameterValues":[]}